### ISSUE TITLE
Ignore __MACOSX folder

### ISSUE THREAD

**Issue by KerningChameleon** [matortheeternal/mod-analyzer#16]
Attempted Analysis of [Dwemer Certified](http://www.nexusmods.com/skyrim/mods/10442/) with Mod Analyzer 1.9.1 through Mod Organizer 1.3.11 on Windows 10 (1607). Default archive analyzes as expected, but the optional archive "Ordinator Compatibility Patch by TheBlackKnight3000" fails with this output:

> Analyzing Ordinator Compatibility Patch by TheBlackKnight3000-10442-1-0.zip...
> Calculating MD5 Hash.
> Dwemer Certified Ordinator Perk Patch\.DS_Store
> __MACOSX\Dwemer Certified Ordinator Perk Patch\._.DS_Store
> Dwemer Certified Ordinator Perk Patch\Dwemer Certified Ordinator Perk Compatibility.esp
> __MACOSX\Dwemer Certified Ordinator Perk Patch\._Dwemer Certified Ordinator Perk Compatibility.esp
> __MACOSX\._Dwemer Certified Ordinator Perk Patch
> 
> Getting plugin dump for Dwemer Certified Ordinator Perk Patch\Dwemer Certified Ordinator Perk Compatibility.esp...
> Extracting Dwemer Certified Ordinator Perk Patch\Dwemer Certified Ordinator Perk Compatibility.esp...
> Analyzing Dwemer Certified Ordinator Perk Patch\Dwemer Certified Ordinator Perk Compatibility.esp...
> 
> ModDump v1.2.0.0
> Game: Skyrim
> DataPath: D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\
>  
> Dumping plugin: Dwemer Certified Ordinator Perk Compatibility.esp
> == Building Load Order ==
>  
> == LOAD ORDER ==
> [00] Skyrim.esm
> [01] Dwemer Certified.esp
> [02] Update.esm
> [03] Dragonborn.esm
> [04] Ordinator - Perks of Skyrim.esp
> [05] D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\Dwemer Certified Ordinator Perk Compatibility.esp
>  
> == LOADING RESOURCES ==
> Loading resources from Skyrim - Misc.bsa
> Loading resources from Skyrim - Shaders.bsa
> Loading resources from Skyrim - Textures.bsa
> Loading resources from Skyrim - Interface.bsa
> Loading resources from Skyrim - Animations.bsa
> Loading resources from Skyrim - Meshes.bsa
> Loading resources from Skyrim - Sounds.bsa
> Loading resources from Skyrim - Voices.bsa
> Loading resources from Skyrim - VoicesExtra.bsa
> Loading resources from Dwemer Certified.bsa
> Loading resources from Update.bsa
> Loading resources from Dragonborn.bsa
> Loading resources from Ordinator - Perks of Skyrim.bsa
>  
> == LOADING PLUGINS ==
> Loading Skyrim.esm...
> [D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\Skyrim.esm]
> Loading Dwemer Certified.esp...
> [D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\Dwemer Certified.esp]
> Loading Update.esm...
> [D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\Update.esm]
> Loading Dragonborn.esm...
> [D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\Dragonborn.esm]
> Loading Ordinator - Perks of Skyrim.esp...
> [D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\Ordinator - Perks of Skyrim.esp]
> Loading Dwemer Certified Ordinator Perk Compatibility.esp...
> [D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\Dwemer Certified Ordinator Perk Compatibility.esp]
>  
> == DUMP ==
> Filename: Dwemer Certified Ordinator Perk Compatibility.esp
> IsESM: False
> Description
> 
> Author: DEFAULT
> Hash: CA1EB1B9
> File size: 5.89 KB
> Masters
> Skyrim.esm
> Dwemer Certified.esp
> Ordinator - Perks of Skyrim.esp
> 
> Number of records: 8
> Number of overrides: 6
> Record groups:
> sig: [AVIF]  Records:    4, Overrides:    4
> sig: [PERK]  Records:    2, Overrides:    2
> Overrides: 6
> Sig: [AVIF]  FormID: 00000450
> Sig: [AVIF]  FormID: 0000045D
> Sig: [AVIF]  FormID: 000005FA
> Sig: [AVIF]  FormID: 00000618
> Sig: [PERK]  FormID: 010012CF
> Sig: [PERK]  FormID: 01001833
> Errors:
>  [AVIF:000005FA] ITM
>  [AVIF:00000618] ITM
>  
> 
> Getting plugin dump for __MACOSX\Dwemer Certified Ordinator Perk Patch\._Dwemer Certified Ordinator Perk Compatibility.esp...
> Extracting __MACOSX\Dwemer Certified Ordinator Perk Patch\._Dwemer Certified Ordinator Perk Compatibility.esp...
> Analyzing __MACOSX\Dwemer Certified Ordinator Perk Patch\._Dwemer Certified Ordinator Perk Compatibility.esp...
> 
> Dumping plugin: ._Dwemer Certified Ordinator Perk Compatibility.esp
> == Building Load Order ==
> Exception Dumping D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\._Dwemer Certified Ordinator Perk Compatibility.esp
> Expected header signature TES4, found  in file "D:\Games\SteamLibraryHDD\steamapps\common\Skyrim\data\._Dwemer Certified Ordinator Perk Compatibility.esp"
> Failed to analyze plugin.
> Exception: Failed to analyze plugin ._Dwemer Certified Ordinator Perk Compatibility.esp
>  
> 
> Plugin dump failed.
>    at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeEntries()
>    at ModAnalyzer.Domain.ModAnalyzerService.BackgroundWork(Object sender, DoWorkEventArgs e)
> Analysis failed.

Looking at the output, there seems to be two copies of the patch: one in an ordinary data structure, and one under the "__MACOSX" directory structure and prefixed with "._". The regular directory structure esp appears to analyze fine, but the other one makes Mod Analyzer choke. I don't know why the archive was packaged in this manner, but my best guess is that is what's throwing the Analyzer for a loop.

**Comment by matortheeternal** [comment]
The mod author packaged the mod archive on a mac.  Macs create these weird files in the __MACOSX folder in archives, I don't know the reason why.

## Short term solution
A short term solution for you could be to delete the __MACOSX folder from the archive.  This will change the CRC32 hash and file size of the archive, but at least you can complete the analysis.

## Ignore __MACOSX folder
A direct fix for this issue would be me adding some code to ignore files in the __MACOSX folder when analyzing an archive.

## Developer build
My developer build for Mod Analyzer 2 has support for ignoring plugins that fail to analyze instead of always causing the analysis to abort.  When MA2 is released this feature should address this and other similar issues.

**Comment by matortheeternal** [comment]
Code to ignore the folder has been included in MA2.  Update will be coming soon.
