### ISSUE TITLE
Smooth blade draw and Sheathe FOMOD

### ISSUE THREAD

**Issue by angrmgmt** [matortheeternal/mod-analyzer#5]
Mod Analyzer is not pleased:

![image](https://cloud.githubusercontent.com/assets/7545532/19214786/df86cf6e-8d40-11e6-9985-7f58c7480837.png)

[Smooth blade draw and Sheathe](http://www.nexusmods.com/skyrim/mods/1117/?)

Windows 10 x64 v.1607, run from Mod Organizer v1.3.11 with full LO.  The FOMOD lets you select which sound options (dagger, 2h, etc.) you want, and whether or not to install the Auto Dynamic Sneak plugin (ADS.esp).

**Comment by TGWArdent** [comment]
Same issue with RaceCompatibility for Skyrim & Dawnguard  FOMOD, same setup.

"Analyzing RaceCompatibility All-in-One NMM installer-24168-1-99.7z...
Parsing FOMOD Options
FOMOD Config Extracted

Object reference not set to an instance of an object.
Analysis failed."

**Comment by matortheeternal** [comment]
Fixed in the latest version, v1.6.

Tested with the Smooth blade draw and Sheathe archive.
