### ISSUE TITLE
Issue: errors with paths

### ISSUE THREAD

**Issue by nesterenko-kv** [matortheeternal/mod-analyzer#7]
You should avoid concatenation of string when u work with path - use Path.Combine everywhere.
Avoid relative path, use absolute, ex. in AnalysisViewModel `Process.Start("output")`, e.t.c.

**Comment by matortheeternal** [comment]
Have you actually had errors, or are you just commenting on code style?

**Comment by nesterenko-kv** [comment]
![image](https://cloud.githubusercontent.com/assets/10574210/20454225/234a811e-ae43-11e6-9f0d-edd79512f2e8.png)
Yep, I have an error. 

> ... could not find a part of the way...

**Comment by nesterenko-kv** [comment]
Find the main root of this issue - I don't have Steam installed, so the game in registry isn't in `\SOFTWARE\Bethesda Softworks\`, nor in `\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App` .

U should add the option to choose the path to the game in ur lib.
